client_id = "6c4ea87dbc56b998f87864fd64fa8a07"
name = "CatalogFlow: B2B Order Catalog"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = [ "products/create", "products/update", "products/delete" ]
uri = "/api/webhooks/products"

[[webhooks.subscriptions]]
topics = [ "collections/create", "collections/update", "collections/delete" ]
uri = "/api/webhooks/collections"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/api/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request" ]
uri = "/api/webhooks/compliance/customers-data-request"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/redact" ]
uri = "/api/webhooks/compliance/customers-redact"

[[webhooks.subscriptions]]
compliance_topics = [ "shop/redact" ]
uri = "/api/webhooks/compliance/shop-redact"

[access_scopes]
scopes = "read_products,read_inventory,write_draft_orders,read_draft_orders"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = []

[build]
automatically_update_urls_on_dev = true
dev_store_url = "catalogflow-test-store.myshopify.com"
